@startuml
left to right direction
skinparam packageStyle rectangle
actor "Docente" as Docente
boundary "Pantalla Calificaciones" as Pantalla
control "Gestor Notas" as Gestor
entity "Historial Académico" as BDAcademico
Docente --> Pantalla : Captura notas Bachillerato (ordinario)
Pantalla --> Gestor : Envía parciales
Gestor --> BDAcademico : Valida criterios preparatoria y guarda
BDAcademico --> Gestor : Éxito
Gestor --> Pantalla : Muestra confirmación
Pantalla --> Docente : Confirma registro
@enduml
